# Generated by Django 4.0.4 on 2022-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='varsta_Pacient',
            field=models.IntegerField(default='10'),
        ),
    ]
