# Generated by Django 4.0.4 on 2022-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0002_pacient_varsta_pacient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='CNP_Pacient',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='varsta_Pacient',
            field=models.IntegerField(default='1'),
        ),
    ]
