# Generated by Django 4.0.4 on 2022-06-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0003_alter_pacient_cnp_pacient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fise_prezentare',
            old_name='Pacient',
            new_name='pacient_id',
        ),
        migrations.AlterField(
            model_name='fise_internari',
            name='Data_externare_internare',
            field=models.DateField(),
        ),
    ]
