# Generated by Django 4.0.4 on 2022-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestiune', '0006_rename_pacient_fise_internari_pacient'),
    ]

    operations = [
        migrations.AddField(
            model_name='fise_internari',
            name='CNP_Pacient',
            field=models.BigIntegerField(default='1234567891234'),
        ),
        migrations.AddField(
            model_name='fise_prezentare',
            name='CNP_Pacient',
            field=models.BigIntegerField(default='1234567891234'),
        ),
    ]
